Feature/keyvault secret
stone-payments/provider-azure pull request #2
Opened 2021-09-08 16:14 UTC by G5Olivieri

### Description of your changes

Add support for Azure Key Vault Secret.
The Key Vault Secret implementation only manage Key Vault Secret, so the Key Vault must be created early.

I have:

- [x] Read and followed Crossplane's [contribution process].
- [x] Run `make reviewable test` to ensure this PR is ready for review.

### How has this code been tested

- Unit tests
- Manually tested

[contribution process]: https://git.io/fj2m9

2021-09-10 13:12 UTC, ferro-vizir requested changes

2021-09-10 13:12 UTC, ferro-vizir commented on apis/keyvault/keyvault.go
> +Copyright 2019 The Crossplane Authors.
Change year to 2021

2021-09-10 13:12 UTC, ferro-vizir commented on apis/keyvault/v1alpha1/doc.go
> +Copyright 2019 The Crossplane Authors.
Change year to 2021

2021-09-10 13:12 UTC, ferro-vizir commented on apis/keyvault/v1alpha1/keyvault_secret_types.go
> +Copyright 2019 The Crossplane Authors.
Change year to 2021

2021-09-10 13:12 UTC, ferro-vizir commented on apis/keyvault/v1alpha1/register.go
> +Copyright 2019 The Crossplane Authors.
Change year to 2021

2021-09-10 13:12 UTC, ferro-vizir commented on pkg/clients/keyvault/secret/keyvault_secret.go
> +package secret
Add documentation

2021-09-10 13:12 UTC, ferro-vizir commented on pkg/clients/keyvault/secret/fake/fake.go
> +package fake
Add documentation

2021-09-10 13:12 UTC, ferro-vizir commented on pkg/controller/keyvault/secret/keyvault_secret.go
> +Copyright 2019 The Crossplane Authors.
Change year to 2021

2021-09-15 12:44 UTC, cnatan approved these changes

2021-09-15 12:46 UTC, merged